<a href="https://colab.research.google.com/github/stephenchenKL/pytorch_tensor/blob/main/view_squeeze_unsqueeze.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


Create a tensor of *1D*.

In [2]:
a = torch.tensor(list(range(9)))
a,a.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([9]))

TORCH.TENSOR.VIEW
Tensor.view(*shape) → Tensor
Returns a new tensor with the same data as the self tensor but of a different shape.

The returned tensor **shares the same data** and must have the **same number of elements**, but may have a different size. 

In [3]:
b = a.view(3,3)
b, b.shape

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]), torch.Size([3, 3]))

In [4]:
b911 = a.view(9,1,1) # b911 is a tensor which consists of 9 rows of item (b911[0] to b911[8]); each item (b911[i]) is a Size([1, 1]) tensor)
temp = b911[1]
temp2 = b911[1][0]
b911, b911.shape, b911[1].shape, temp, temp2.shape, temp2

(tensor([[[0]],
 
         [[1]],
 
         [[2]],
 
         [[3]],
 
         [[4]],
 
         [[5]],
 
         [[6]],
 
         [[7]],
 
         [[8]]]),
 torch.Size([9, 1, 1]),
 torch.Size([1, 1]),
 tensor([[1]]),
 torch.Size([1]),
 tensor([1]))

In [5]:
d = a.view(3, 3, -1) # return tensor of shape tensor.Size([3, 3, 1])
d2 = a.view(1, 1, -1) # return tensor of shape tensor.Size([1, 1, 9])
d3 = a.view(1, 9, -1) # return tensor of shape tensor.Size([1, 9, 1])
d, d.shape, d2, d2.shape, d3, d3.shape

(tensor([[[0],
          [1],
          [2]],
 
         [[3],
          [4],
          [5]],
 
         [[6],
          [7],
          [8]]]),
 torch.Size([3, 3, 1]),
 tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8]]]),
 torch.Size([1, 1, 9]),
 tensor([[[0],
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8]]]),
 torch.Size([1, 9, 1]))

TORCH.UNSQUEEZE
torch.unsqueeze(input, dim) → Tensor
Returns a new tensor with a dimension of size one inserted at the specified position.

The returned tensor shares the same underlying data with this tensor.

A dim value within the range [-input.dim() - 1, input.dim() + 1) can be used. Negative dim will correspond to unsqueeze() applied at dim = dim + input.dim() + 1.

In [6]:
d0 = b.view(3,3).unsqueeze(0)
d0, d0.shape

(tensor([[[0, 1, 2],
          [3, 4, 5],
          [6, 7, 8]]]), torch.Size([1, 3, 3]))

In [7]:
d2 = b.unsqueeze(2) # or b.unsqueeze(-1)
d2, d2.shape

(tensor([[[0],
          [1],
          [2]],
 
         [[3],
          [4],
          [5]],
 
         [[6],
          [7],
          [8]]]), torch.Size([3, 3, 1]))

In [8]:
d1 =  b.unsqueeze(1) 
d1, d1.shape

(tensor([[[0, 1, 2]],
 
         [[3, 4, 5]],
 
         [[6, 7, 8]]]), torch.Size([3, 1, 3]))

In [9]:
e119 = a.unsqueeze(0).unsqueeze(0)
e119, e119.shape

(tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8]]]), torch.Size([1, 1, 9]))

In [10]:
e19 = a.unsqueeze(0)
e19, e19.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]]), torch.Size([1, 9]))

In [11]:
e91 = a.unsqueeze(1)
e91, e91.shape

(tensor([[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8]]), torch.Size([9, 1]))

In [12]:
e191 = a.unsqueeze(1).unsqueeze(0)
e191, e191.shape

(tensor([[[0],
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8]]]), torch.Size([1, 9, 1]))

In [13]:
e911 = a.unsqueeze(1).unsqueeze(1)
e911, e911.shape

(tensor([[[0]],
 
         [[1]],
 
         [[2]],
 
         [[3]],
 
         [[4]],
 
         [[5]],
 
         [[6]],
 
         [[7]],
 
         [[8]]]), torch.Size([9, 1, 1]))